name: $(Date:yyyyMMdd)$(Rev:.r)-ArgoCD
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'Ashraf_aws'
  AWS_REGION: 'eu-west-1'
  CLUSTER_NAME: 'eks-platform-nonprod-v2-cluster'

pool:
  name: queue-bebo_mohammed
jobs:
- job: ArgoSync
  displayName: 'ArgoCD Sync / Rollout'
  steps:
  - checkout: self

  - task: AWSShellScript@1
    displayName: Configure kubeconfig
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        
        if [ -z "$(CLUSTER_NAME)" ]; then
          echo "Error: CLUSTER_NAME variable is not set."
          exit 1
        fi

        echo "Checking if cluster $(CLUSTER_NAME) exists..."
        if ! aws eks describe-cluster --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)" >/dev/null 2>&1; then
           echo "##[warning]Cluster $(CLUSTER_NAME) not found. Skipping kubeconfig setup."
           echo "##vso[task.setvariable variable=CLUSTER_EXISTS]false"
           exit 0
        fi

        echo "Connecting to cluster: $(CLUSTER_NAME)..."
        aws eks update-kubeconfig --name "$(CLUSTER_NAME)" --region "$(AWS_REGION)"
        
        # Get API Gateway URL for ingress annotations
        APIGW_URL=$(aws apigatewayv2 get-apis --query "Items[?Name=='eks-platform-nonprod-v2-api-v2-nonprod'].ApiEndpoint" --output text)
        echo "Found API Gateway: $APIGW_URL"
        echo "##vso[task.setvariable variable=APIGW_URL]$APIGW_URL"
        echo "##vso[task.setvariable variable=CLUSTER_EXISTS]true"

  - task: Docker@2
    displayName: Docker Login
    inputs:
      command: login
      containerRegistry: 'Ashraf_docker'

  - task: Bash@3
    displayName: Export Docker Credentials
    inputs:
      targetType: inline
      script: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        CONFIG_FILE="$DOCKER_CONFIG/config.json"
        AUTH_STRING=$(python3 -c "import json; data = json.load(open('$CONFIG_FILE')); print(list(data['auths'].values())[0]['auth'])")
        DECODED_AUTH=$(echo "$AUTH_STRING" | base64 -d)
        DOCKER_USERNAME=$(echo "$DECODED_AUTH" | cut -d: -f1)
        DOCKER_PASSWORD=$(echo "$DECODED_AUTH" | cut -d: -f2-)
        echo "##vso[task.setvariable variable=DOCKER_USERNAME]$DOCKER_USERNAME"
        echo "##vso[task.setvariable variable=DOCKER_PASSWORD;isSecret=true]$DOCKER_PASSWORD"

  - task: AWSShellScript@1
    displayName: Deploy Motivational App (Helm)
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euxo pipefail
        
        if [ "$(CLUSTER_EXISTS)" == "false" ]; then
           exit 0
        fi

        kubectl delete secret regcred -n ashraf --ignore-not-found=true
        kubectl create secret docker-registry regcred \
          --namespace ashraf \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username="$(DOCKER_USERNAME)" \
          --docker-password="$(DOCKER_PASSWORD)" \
          --docker-email=masrhef@gmail.com
        
        if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        fi

        # 1. Nuclear Cleanup: Clear any stuck/abandoned states
        echo "Nuclear Cleanup: Removing existing release if present..."
        helm uninstall motivational-app -n ashraf || true
        kubectl delete jobs -n ashraf -l app.kubernetes.io/instance=motivational-app --ignore-not-found=true
        kubectl delete deployment motivational-app -n ashraf --ignore-not-found=true

        # 2. Advanced Connectivity Check
        EKS_URL=$(kubectl config view -o jsonpath='{.clusters[0].cluster.server}')
        EKS_HOST=$(echo "$EKS_URL" | cut -d/ -f3)
        echo "EKS Host: $EKS_HOST"
        
        echo "Diagnostic: nslookup $EKS_HOST"
        nslookup "$EKS_HOST" || echo "##[warning] DNS lookup failed"

        # 3. Safe Values Generation
        if [ -z "${APIGW_URL:-}" ] || [ "$APIGW_URL" == "None" ]; then
          echo "##[warning] APIGW_URL is empty. Using fallback localhost."
          FINAL_APIGW="http://localhost"
        else
          FINAL_APIGW="$APIGW_URL"
        fi

        echo "ingress:" > dynamic-values.yaml
        echo "  annotations:" >> dynamic-values.yaml
        echo "    nginx.ingress.kubernetes.io/auth-signin: \"${FINAL_APIGW}/oauth2/start?rd=\$escaped_request_uri\"" >> dynamic-values.yaml
        
        echo "Generated values:"
        cat dynamic-values.yaml

        # 4. Final Deploy Attempt with Failure Trap
        echo "Starting Helm upgrade..."
        if ! helm upgrade --install motivational-app ./motivational-app \
          --namespace ashraf --create-namespace \
          --set image.tag="latest" \
          -f dynamic-values.yaml \
          --wait --timeout 5m \
          --debug; then
            echo "##[error] Helm upgrade failed or timed out. Collecting diagnostics..."
            echo "Deployment Pods:"
            kubectl get pods -n ashraf -l app.kubernetes.io/instance=motivational-app
            echo "Pod Descriptions (Events):"
            kubectl describe pods -n ashraf -l app.kubernetes.io/instance=motivational-app
            echo "Recent Logs for Containers:"
            kubectl logs -n ashraf -l app.kubernetes.io/instance=motivational-app --all-containers=true --tail=50
            exit 1
        fi

        echo "Deployment Succeeded. Current Status:"
        kubectl get pods -n ashraf -l app.kubernetes.io/instance=motivational-app
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
