name: $(Date:yyyyMMdd)$(Rev:.r)-Release
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'Ashraf_aws'
  AWS_REGION: 'eu-west-1'
  IMAGE_REPOSITORY: 'yabani1/ashroo'

jobs:
- job: Release
  displayName: 'Build and Release Docker Image'
pool:
  name: queue-bebo_mohammed
  steps:
    - checkout: self

    # 1. Build and Push
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'Ashraf_docker'
        repository: $(IMAGE_REPOSITORY)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
