name: $(Date:yyyyMMdd)$(Rev:.r)-Release
trigger: none

pr: none

variables:
  AWS_SERVICE_CONNECTION: 'Ashraf_aws'
  AWS_REGION: 'eu-west-1'
  IMAGE_REPOSITORY: 'yabani1/ashroof'
  # OPTIMIZATION: Set this variable in Azure DevOps Library to avoid running Terraform to find it.
   
pool:
 vmImage: ubuntu-latest


jobs:
- job: Release
  displayName: 'Build and Release Docker Image'
pool:
  vmImage: ubuntu-latest
  steps:
  - checkout: self

  # 1. Build and Push (Does not need Cluster Access)
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'docker'
      repository: yabani1/ashroof
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  # 2. Deploy via Kubectl (Optional - only if you want to force update without ArgoCD)
  # Keeping this simple: Release just builds. ArgoCD Pipeline handles the rest.
